import { join } from 'path'
import { writeFileSync } from 'fs'
import { agentWorkspaceDir } from './paths'

// Claude Code reads project-scoped CLAUDE.md by walking up from its cwd;
// Codex CLI does the same for AGENTS.md. Both land in the shared agent
// workspace dir (see paths.ts) so the guidance only applies to sessions
// started from Applyer's terminal.
const INSTRUCTIONS = `# Applyer — Job Search Agent

This is Applyer's embedded terminal working directory. An MCP server named
\`applyer\` is available with tools for autonomous job hunting, backed by the
app's local job-tracking database and a real browser:

- \`get_profile\` — the candidate's profile (contact info, desired roles,
  skills, salary expectations) and uploaded documents. Call this first so you
  know who you're searching for and how to judge a match.
- \`search_jobs\` — search job postings by keyword (LinkedIn/Indeed keyword
  search; other sources are per-company boards with no search endpoint — use
  \`get_job_details\` with a specific career-page URL for those instead).
- \`get_job_details\` — fetch the full description, location, and application
  info for a single job posting URL.
- \`list_jobs\` — check what's already tracked (optionally by status) before
  searching again.
- \`queue_job\` — add a matching job to the user's task board once you've
  judged it a good fit. Deduplicated by URL, safe to call again.
- \`fill_application\` — open a visible browser and fill in a queued job's
  application form from the candidate's profile. Never submits — the user
  reviews and submits it themselves.
- \`flag_failure\` — mark a job Failed with a reason when you can't proceed
  with it (e.g. a login wall or an expired listing).
- \`exclude_job\` — permanently blacklist a job posting URL: removed from the
  board if tracked, never returned by \`search_jobs\` again, can't be
  re-queued. ONLY call this when the user has explicitly asked to exclude,
  blacklist, hide, or stop seeing a posting or postings matching some stated
  criteria (e.g. "put job postings that are not remote on the exclusion
  list", "exclude that one", "I never want to see Foo Corp jobs again").
  Never call it just because you personally judge a job a bad match — for
  that, simply don't queue it.

When the user asks you to find, search for, track, or apply to jobs, use
these tools instead of browsing job sites manually — they operate on the
same job board the user sees in the app. Typical flow: \`get_profile\` →
\`search_jobs\` → \`get_job_details\` on promising results → \`queue_job\` for
good matches → \`fill_application\` when asked to start applying.

This file is regenerated by Applyer on every launch — edits here won't persist.
`

export function writeAgentInstructions(): void {
  const dir = agentWorkspaceDir()
  writeFileSync(join(dir, 'CLAUDE.md'), INSTRUCTIONS)
  writeFileSync(join(dir, 'AGENTS.md'), INSTRUCTIONS)
}
